### ISSUE TITLE
Next.js is throwing a console error at admin build time

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1061]
```
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
    at Overflow (/home/gabek/src/owncast-admin/node_modules/rc-overflow/lib/Overflow.js:42:32)
    at InheritableContextProvider (/home/gabek/src/owncast-admin/node_modules/rc-menu/lib/context/MenuContext.js:39:23)
    at Menu (/home/gabek/src/owncast-admin/node_modules/rc-menu/lib/Menu.js:76:32)
    at InternalMenu (/home/gabek/src/owncast-admin/node_modules/antd/lib/menu/index.js:71:37)
    at Menu (/home/gabek/src/owncast-admin/node_modules/antd/lib/menu/index.js:162:37)
    at div
    at aside
    at Sider (/home/gabek/src/owncast-admin/node_modules/antd/lib/layout/Sider.js:74:31)
    at section
    at BasicLayout (/home/gabek/src/owncast-admin/node_modules/antd/lib/layout/layout.js:93:34)
    at Layout (/home/gabek/src/owncast-admin/node_modules/antd/lib/layout/layout.js:61:37)
    at MainLayout (webpack-internal:///./components/main-layout.tsx:59:5)
    at AlertMessageProvider (webpack-internal:///./utils/alert-message-context.tsx:22:3)
    at ServerStatusProvider (webpack-internal:///./utils/server-status-context.tsx:89:3)
    at App (webpack-internal:///./pages/_app.tsx:70:3)
    at AppContainer (/home/gabek/src/owncast-admin/node_modules/next/dist/next-server/server/render.js:28:952)

```

**Comment by gabek** [comment]
This looks to be an issue with the `antd` library we're using with the admin.  We should try updating to the most recent version.

**Comment by gabek** [comment]
Issue seems to be this: https://github.com/ant-design/ant-design/issues/31025

**Comment by gabek** [comment]
Now issue is being tracked at: https://github.com/ant-design/ant-design/issues/30396

**Comment by gabek** [comment]
Somebody seems to have found a workaround for this until Ant fixes it:

https://github.com/ant-design/ant-design/issues/30396#issuecomment-964318877

**Comment by gabek** [comment]
Closing since this is a next+ant issue and there's nothing we can do about it, and it's also not breaking anything.
