### ISSUE TITLE
[bug] Follow request from GoToSocial causes nil pointer exception

### ISSUE THREAD

**Issue by tsmethurst** [owncast/owncast#1955]
Here's the follow request as it arrives in the inbox:

```
 {"@context":"https://www.w3.org/ns/activitystreams","actor":"https://goblin.technology/users/tobi","id":"https://goblin.technology/users/tobi/follow/017E3ZYTD3V02DYA69E6D42S6T","object":"https://live.superseriousbusiness.org/federation/user/streamer","to":"https://live.superseriousbusiness.org/federation/user/streamer","type":"Follow"} 
```

And here's the panic:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x173ccd4]

goroutine 74 [running]:
github.com/owncast/owncast/activitypub/apmodels.MakeActorFromExernalAPEntity({0x7f18e3e6aad8, 0xc000208600})
	/build/activitypub/apmodels/actor.go:84 +0x274
github.com/owncast/owncast/activitypub/resolvers.GetResolvedActorFromIRI.func1({0x19b0a00?, 0x0?}, {0x24110e8?, 0xc000208600})
	/build/activitypub/resolvers/resolve.go:131 +0x4f
github.com/go-fed/activity/streams.JSONResolver.Resolve.func1({0xc0005200aa, 0x6})
	/go/pkg/mod/github.com/owncast/activity@v1.0.1-0.20211229051252-7821289d4026/streams/gen_json_resolver.go:691 +0x3d13
github.com/go-fed/activity/streams.JSONResolver.Resolve({{0xc0005bd380?, 0x2fc?, 0xc00040ba88?}}, {0x23ee618, 0xc000036060}, 0xc00082c120)
	/go/pkg/mod/github.com/owncast/activity@v1.0.1-0.20211229051252-7821289d4026/streams/gen_json_resolver.go:888 +0x171
github.com/owncast/owncast/activitypub/resolvers.Resolve({0x23ee618, 0xc000036060}, {0xc000846000, 0x2fc, 0x380}, {0xc0005bd380?, 0x0?, 0x0?})
	/build/activitypub/resolvers/resolve.go:35 +0x159
github.com/owncast/owncast/activitypub/resolvers.ResolveIRI({0x23ee618, 0xc000036060}, {0xc0006de1c0, 0x2d}, {0xc0005bd380, 0x3, 0x3})
	/build/activitypub/resolvers/resolve.go:72 +0x245
github.com/owncast/owncast/activitypub/resolvers.GetResolvedActorFromIRI({0xc0006de1c0, 0x2d})
	/build/activitypub/resolvers/resolve.go:157 +0x245
github.com/owncast/owncast/activitypub/inbox.Verify(0xc0003c5000)
	/build/activitypub/inbox/worker.go:74 +0x358
github.com/owncast/owncast/activitypub/inbox.handle({0xc0003c5000, {0xc0001ef5a6, 0x8}, {0xc0006e4000, 0x151, 0x200}})
	/build/activitypub/inbox/worker.go:23 +0x65
github.com/owncast/owncast/activitypub/inbox.worker(0x0?, 0x0?)
	/build/activitypub/inbox/workerpool.go:40 +0x108
created by github.com/owncast/owncast/activitypub/inbox.InitInboxWorkerPool
	/build/activitypub/inbox/workerpool.go:26 +0x51
```

This is with the latest version of owncast from develop. I'm gonna try and track this one down myself :)

**Comment by tsmethurst** [comment]
Oh I know what's happening... owncast assumes the publicKeyID is the same as the actor IRI, but in GoToSocial it's not, so it's trying to dereference a public key representation as a full-ass actor. I'll make a fix for it :)
