### ISSUE TITLE
Owncast crashes occasionally when sending push notifications

### ISSUE THREAD

**Issue by ghost** [owncast/owncast#2855]
### Share your bug report, feature request, or comment.

It has happened to me a few times now that Owncast just crashed.

Unfortunately, I can't really reproduce the problem reliably.
Maybe others have the problem too and can share some feedback?

Log output:

```
owncast-dev  | time="2023-03-21T15:47:40Z" level=info msg="Owncast vdev-docker (20230321)"
owncast-dev  | time="2023-03-21T15:47:40Z" level=info msg="Video transcoder started using x264 with 1 stream variants."
owncast-dev  | time="2023-03-21T15:47:40Z" level=info msg="RTMP is accepting inbound streams on port 1935."
owncast-dev  | time="2023-03-21T15:47:40Z" level=info msg="Web server is listening on IP 0.0.0.0 port 8080."
owncast-dev  | time="2023-03-21T15:47:40Z" level=info msg="The web admin interface is available at /admin."
owncast-dev  | time="2023-03-21T15:47:50Z" level=info msg="Inbound stream connected."
owncast-dev  | time="2023-03-21T15:47:50Z" level=info msg="Video transcoder started using x264 with 1 stream variants."
owncast-dev  | panic: runtime error: invalid memory address or nil pointer dereference
owncast-dev  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xa75c5c]
owncast-dev  |
owncast-dev  | goroutine 107 [running]:
owncast-dev  | github.com/owncast/owncast/notifications/browser.(*Browser).Send(0xc0059b4600, {0xc005860d80, 0x161}, {0xc005700cc0?, 0x0?}, {0xc005543ab0?, 0x0?})
owncast-dev  | 	/build/notifications/browser/browser.go:75 +0x21c
owncast-dev  | github.com/owncast/owncast/notifications.(*Notifier).notifyBrowserPush(0xc000521e60)
owncast-dev  | 	/build/notifications/notifications.go:98 +0x146
owncast-dev  | github.com/owncast/owncast/notifications.(*Notifier).Notify(0xc000521e60)
owncast-dev  | 	/build/notifications/notifications.go:146 +0x25
owncast-dev  | github.com/owncast/owncast/core.startLiveStreamNotificationsTimer.func1({0x3f8eaf8, 0xc000038780})
owncast-dev  | 	/build/core/streamState.go:188 +0x1c7
owncast-dev  | created by github.com/owncast/owncast/core.startLiveStreamNotificationsTimer
owncast-dev  | 	/build/core/streamState.go:169 +0xaa
owncast-dev exited with code 2
```

Environment:

OS: Debian 11
Docker Version: Docker version 23.0.1, build a5ee5b1
Owncast Build: vdev-docker (20230321) - 159bf7912c70ecdeb6f2fe17f58cb816fc5de44a

**Comment by gabek** [comment]
I haven't heard of anybody else experiencing this, but thank you for reporting it. Looks to be browser push notification related. I'll fix it up, thanks again!
