### ISSUE TITLE
Fix NotifyReminderPopup warning: findDOMNode is deprecated in StrictMode.

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#3034]
### Share your bug report, feature request, or comment.

Looks like we need to change how `NotifyReminderPopup` is displayed.

![image](https://github.com/owncast/owncast/assets/414923/18508fd4-cc63-4e63-b224-dba9573eea8c)

```
client.js?4d30:1 Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Trigger which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
    at button
    at Wave (webpack-internal:///./node_modules/antd/es/_util/wave.js:52:90)
    at InternalButton (webpack-internal:///./node_modules/antd/es/button/button.js:114:30)
    at NotifyButton (webpack-internal:///./components/action-buttons/NotifyButton.tsx:27:11)
    at Trigger (webpack-internal:///./node_modules/rc-trigger/es/index.js:78:92)
    at Tooltip (webpack-internal:///./node_modules/rc-tooltip/es/Tooltip.js:22:32)
    at eval (webpack-internal:///./node_modules/antd/es/tooltip/index.js:86:62)
    at eval (webpack-internal:///./node_modules/antd/es/popover/index.js:37:34)
    at NotifyReminderPopup (webpack-internal:///./components/ui/NotifyReminderPopup/NotifyReminderPopup.tsx:31:11)
    at LoadableComponent (webpack-internal:///./node_modules/next/dist/shared/lib/loadable.js:87:9)
    at div
    at ActionButtonRow (webpack-internal:///./components/action-buttons/ActionButtonRow/ActionButtonRow.tsx:12:11)
    at div
    at ActionButtons (webpack-internal:///./components/ui/Content/ActionButtons.tsx:44:11)
```

**Comment by yk-jp** [comment]
Hi, can I give it a go if it's not in rush to be fixed?

**Comment by gabek** [comment]
No rush, it's all yours!  Thanks!

**Comment by yk-jp** [comment]
@gabek 

Hi, I've set up the env on my local machine, but I don't see the error when localhost:3000 gets opened.
Can you confirm that the warning is still present or can you give me where the warning occurs?

I also found the same open issue, https://github.com/owncast/owncast/issues/2345
It seems to me that the current `antd` is not version 5 described in package.json.

**Comment by gabek** [comment]
The `NotifyReminderPopup` needs to be displayed for the error relating to it to show. I'm not sure why I thought it was connected to Ant 5 because the error says to migrate to using a `ref` and I don't think I ever actually tried that. It might also be that I looked deeper into it before and I just forget.

![image](https://github.com/owncast/owncast/assets/414923/53c9713a-5452-41d2-87c2-0b2ca7562a53)
