### ISSUE TITLE
Deleting all stream keys causes client-side errors

### ISSUE THREAD

**Issue by IdrisFallout** [owncast/owncast#3114]
### Share your bug report, feature request, or comment.

I am unable to add a stream key on the web interface. It throws an error at http://192.168.43.28:8080/admin/config/server/ and in the Stream keys section. Here is the error message: "Application error: a client-side exception has occurred (see the browser console for more information)."
I am not sure how i can set the stream key via the cli arguments

**Comment by gabek** [comment]
Could you provide the actual error log?

**Comment by IdrisFallout** [comment]
The error occurred once i deleted all stream keys. I can no longer access
the Stream key section. My only solution is to delete my server and
redownload everything

**Comment by gabek** [comment]
If you could share the actual error log from your browser that'd be awesome.

**Comment by gabek** [comment]
```
client.js:1 Error: must provide at least one valid stream key
    at fetchData (apis.ts:147:11)
    at async saveKeys (StreamKeys.tsx:27:5)
console.error @ client.js:1
react-dom.development.js:14887 Uncaught Error: Objects are not valid as a React child (found: [object Error]). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (react-dom.development.js:14887:1)
    at reconcileChildFibers (react-dom.development.js:15828:1)
    at reconcileChildren (react-dom.development.js:19167:1)
    at updateHostComponent (react-dom.development.js:19924:1)
    at beginWork (react-dom.development.js:21618:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
    at workLoopSync (react-dom.development.js:26466:1)
    at renderRootSync (react-dom.development.js:26434:1)
    at performConcurrentWorkOnRoot (react-dom.development.js:25738:1)
    at workLoop (scheduler.development.js:266:1)
    at flushWork (scheduler.development.js:239:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:533:1)
react-dom.development.js:14887 Uncaught Error: Objects are not valid as a React child (found: [object Error]). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (react-dom.development.js:14887:1)
    at reconcileChildFibers (react-dom.development.js:15828:1)
    at reconcileChildren (react-dom.development.js:19167:1)
    at updateHostComponent (react-dom.development.js:19924:1)
    at beginWork (react-dom.development.js:21618:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
    at workLoopSync (react-dom.development.js:26466:1)
    at renderRootSync (react-dom.development.js:26434:1)
    at recoverFromConcurrentError (react-dom.development.js:25850:1)
    at performConcurrentWorkOnRoot (react-dom.development.js:25750:1)
    at workLoop (scheduler.development.js:266:1)
    at flushWork (scheduler.development.js:239:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:533:1)
client.js:1 The above error occurred in the <div> component:

    at div
    at div
    at div
    at DomWrapper (webpack-internal:///./node_modules/rc-motion/es/DomWrapper.js:17:90)
    at eval (webpack-internal:///./node_modules/rc-motion/es/CSSMotion.js:50:32)
    at Alert (webpack-internal:///./node_modules/antd/es/alert/index.js:98:24)
    at div
    at Item (webpack-internal:///./node_modules/antd/es/space/Item.js:15:24)
    at div
    at Space (webpack-internal:///./node_modules/antd/es/space/index.js:51:62)
    at div
    at StreamKeys (webpack-internal:///./components/admin/config/server/StreamKeys.tsx:218:79)
    at div
    at eval (webpack-internal:///./node_modules/rc-tabs/es/TabPanelList/TabPane.js:9:24)
    at DomWrapper (webpack-internal:///./node_modules/rc-motion/es/DomWrapper.js:17:90)
    at eval (webpack-internal:///./node_modules/rc-motion/es/CSSMotion.js:50:32)
    at div
    at div
    at TabPanelList (webpack-internal:///./node_modules/rc-tabs/es/TabPanelList/index.js:27:17)
    at div
    at Tabs (webpack-internal:///./node_modules/rc-tabs/es/Tabs.js:50:17)
    at Tabs (webpack-internal:///./node_modules/antd/es/tabs/index.js:41:17)
    at div
    at PublicFacingDetails (webpack-internal:///./pages/admin/config/server/index.tsx:26:79)
    at RecoilRoot_INTERNAL (webpack-internal:///./node_modules/recoil/es/index.js:4473:3)
    at RecoilRoot (webpack-internal:///./node_modules/recoil/es/index.js:4639:5)
    at main
    at eval (webpack-internal:///./node_modules/antd/es/layout/layout.js:65:25)
    at eval (webpack-internal:///./node_modules/antd/es/layout/layout.js:48:66)
    at section
    at eval (webpack-internal:///./node_modules/antd/es/layout/layout.js:79:63)
    at eval (webpack-internal:///./node_modules/antd/es/layout/layout.js:48:66)
    at section
    at eval (webpack-internal:///./node_modules/antd/es/layout/layout.js:79:63)
    at eval (webpack-internal:///./node_modules/antd/es/layout/layout.js:48:66)
    at MainLayout (webpack-internal:///./components/admin/MainLayout.tsx:150:11)
    at AlertMessageProvider (webpack-internal:///./utils/alert-message-context.tsx:17:11)
    at ServerStatusProvider (webpack-internal:///./utils/server-status-context.tsx:123:11)
    at AdminLayout (webpack-internal:///./components/layouts/AdminLayout.tsx:15:11)
    at App (webpack-internal:///./pages/_app.tsx:30:11)
    at PathnameContextProviderAdapter (webpack-internal:///./node_modules/next/dist/shared/lib/router/adapters.js:74:11)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:306:63)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:877:919)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:92:1)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:196:11)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:374:11)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
console.error @ client.js:1
```
