### ISSUE TITLE
Occasional crashes, SIGSEGV

### ISSUE THREAD

**Issue by ghost** [owncast/owncast#3223]
Owncast v0.1.1 (running on Ubuntu Server 22.04) crashes occasionally while leaving this in the log:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x591d00]
goroutine 40 [running]:
net/url.(*URL).String(0x0)
        /usr/local/go/src/net/url/url.go:800 +0x40
github.com/owncast/owncast/activitypub/inbox.handleLikeRequest({0x1ae05e0?, 0x0?}, {0x4ece0e8, 0xc00096a840})
        /build/activitypub/inbox/like.go:16 +0x95
github.com/go-fed/activity/streams.JSONResolver.Resolve.func1({0xc00107e32c, 0x4})
        /go/pkg/mod/github.com/owncast/activity@v1.0.1-0.20211229051252-7821289d4026/streams/gen_json_resolver.go:559 +0x3885
github.com/go-fed/activity/streams.JSONResolver.Resolve({{0xc000e85320?, 0x1b1?, 0xc0006a9e00?}}, {0x4eaf288, 0xc00013e038}, 0xc00031d710)
        /go/pkg/mod/github.com/owncast/activity@v1.0.1-0.20211229051252-7821289d4026/streams/gen_json_resolver.go:888 +0x171
github.com/owncast/owncast/activitypub/resolvers.Resolve({0x4eaf288, 0xc00013e038}, {0xc00095b200, 0x1b1, 0x200}, {0xc000e85320?, 0x0?, 0xc00000e678?})
        /build/activitypub/resolvers/resolve.go:35 +0x159
github.com/owncast/owncast/activitypub/inbox.handle({0xc000e01b00, {0xc000af65e6, 0x6}, {0xc00095b200, 0x1b1, 0x200}})
        /build/activitypub/inbox/worker.go:32 +0x21d
github.com/owncast/owncast/activitypub/inbox.worker(0xc0000341e0?, 0xc000114540?)
        /build/activitypub/inbox/workerpool.go:40 +0x108
created by github.com/owncast/owncast/activitypub/inbox.InitInboxWorkerPool
        /build/activitypub/inbox/workerpool.go:26 +0x51
owncast.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```
I had this with v0.0.13 already for some weeks now. Since this version was outdated already, I just looked at the issues here and saw that a similar issue was reported (and closed) already. So I didn't give it much attention. But after updating to v0.1.1 this keeps going on.
When I turn off the Fediverse features, everything is fine and no crash happens. But since a lot of my viewers use Fediverse auth, it's not the best option to turn that off all the time. :)
I hope this report helps. If you need further info, please ask.

**Comment by gabek** [comment]
Thanks for reporting this!

**Comment by LogalDeveloper** [comment]
Hi @gabek! It looks like this issue might still exist in v0.2.1. We had the [Fireside Fedi](https://stream.firesidefedi.live/) instance crash in the middle of a show today. It gave a very similar looking trace:

```
2025-04-14T22:30:20.898151032Z time="2025-04-14T22:30:20Z" level=info msg="Owncast v0.2.1-linux-64bit (b671e182bf709b695d065e0128017e6963478357)"
2025-04-14T22:30:20.929746626Z time="2025-04-14T22:30:20Z" level=info msg="Saving new web server port number to 8081"
2025-04-14T22:30:20.929759988Z time="2025-04-14T22:30:20Z" level=info msg="Saving new RTMP server port number to 1936"
2025-04-14T22:30:20.931395118Z time="2025-04-14T22:30:20Z" level=info msg="RTMP is accepting inbound streams on port 1936."
2025-04-14T22:30:20.938190141Z time="2025-04-14T22:30:20Z" level=info msg="Web server is listening on port 8081."
2025-04-14T22:30:20.938206266Z time="2025-04-14T22:30:20Z" level=info msg="Configure this server by visiting /admin."
2025-04-15T00:55:33.586333049Z time="2025-04-15T00:55:33Z" level=info msg="Inbound stream connected from 192.168.145.200:60236"
2025-04-15T00:55:33.586947687Z time="2025-04-15T00:55:33Z" level=info msg="Processing video using codec x264 with 3 output qualities configured."
2025-04-15T00:58:03.713745205Z time="2025-04-15T00:58:03Z" level=error msg="ActivityPub destination  failed to send Error: Post \"https://masto.cyclolys.is/users/Cyclolysis/inbox\": dial tcp 176.34.158.35:443: i/o timeout"
2025-04-15T01:59:44.632101932Z panic: runtime error: invalid memory address or nil pointer dereference
2025-04-15T01:59:44.632140949Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x5c5d0c]
2025-04-15T01:59:44.632144155Z 
2025-04-15T01:59:44.632145797Z goroutine 625 [running]:
2025-04-15T01:59:44.632147548Z net/url.(*URL).String(0xc0012dcbd0?)
2025-04-15T01:59:44.632149175Z 	/usr/local/go/src/net/url/url.go:832 +0x2c
2025-04-15T01:59:44.632150956Z github.com/owncast/owncast/activitypub/inbox.handleLikeRequest({0xc0012dc630?, 0xc0012dcab0?}, {0x4094a00, 0xc000bb7348})
2025-04-15T01:59:44.632152690Z 	/build/activitypub/inbox/like.go:24 +0x190
2025-04-15T01:59:44.632154411Z github.com/go-fed/activity/streams.JSONResolver.Resolve.func1({0xc00142fa60, 0x4})
2025-04-15T01:59:44.632156062Z 	/go/pkg/mod/github.com/owncast/activity@v1.0.1-0.20211229051252-7821289d4026/streams/gen_json_resolver.go:559 +0x3603
2025-04-15T01:59:44.632157701Z github.com/go-fed/activity/streams.JSONResolver.Resolve({{0xc0015e13e0?, 0x27f3?, 0xc000d05e10?}}, {0x406e3b8, 0x52b79c0}, 0xc0012dc630)
2025-04-15T01:59:44.632159441Z 	/go/pkg/mod/github.com/owncast/activity@v1.0.1-0.20211229051252-7821289d4026/streams/gen_json_resolver.go:888 +0x163
2025-04-15T01:59:44.632161356Z github.com/owncast/owncast/activitypub/resolvers.Resolve({0x406e3b8, 0x52b79c0}, {0xc000c8a000, 0x27f3, 0x3000}, {0xc0015e13e0?, 0x0?, 0x100000000000000?})
2025-04-15T01:59:44.632163082Z 	/build/activitypub/resolvers/resolve.go:35 +0x155
2025-04-15T01:59:44.632164683Z github.com/owncast/owncast/activitypub/inbox.handle({0xc0004def00, {0xc0006a46d6, 0x6}, {0xc000c8a000, 0x27f3, 0x3000}})
2025-04-15T01:59:44.632166388Z 	/build/activitypub/inbox/worker.go:32 +0x1f6
2025-04-15T01:59:44.632167945Z github.com/owncast/owncast/activitypub/inbox.worker(0x2, 0xc0000e2000)
2025-04-15T01:59:44.632169582Z 	/build/activitypub/inbox/workerpool.go:40 +0xf9
2025-04-15T01:59:44.632171247Z created by github.com/owncast/owncast/activitypub/inbox.InitInboxWorkerPool in goroutine 1
2025-04-15T01:59:44.632173073Z 	/build/activitypub/inbox/workerpool.go:26 +0x58

[... end of output, container restarts automatically ...]
```

Looking at logs going back to January 28, 2025, this Owncast instance first crashed on March 30, 2025 and now crashes regularly with the same trace. Of note on that day, [this](https://loves.tech/channel/scott) user followed the instance. I am not sure if there is relevance between the subscribed user and the crash or not.

My other personal Owncast instance has not exhibited this problem.

**Comment by gabek** [comment]
~~Would you be able to get me the complete log?~~ Nevermind this should be fine.

**Comment by LogalDeveloper** [comment]
Let me know if you do end up wanting it!
