### ISSUE TITLE
Owncast is occasionally crashing

### ISSUE THREAD

**Issue by alyx161** [owncast/owncast#3307]
### Share your bug report, feature request, or comment.

I've seen that my owncast instance is occasionally crashing.

I can't pinpoint precisely what is triggering it, so I can't reproduce it directly, but it happens regularly, as you can see in the logs.
From the 12. to the 13. the instance was a completely inactive newly installed instance with no federation activity (but federation enabled) and no streams.

**System**
OS: Debian 12
Version: Official Docker Image
Platform: ARM64

```
owncast-njionlive  | time="2023-09-12T11:21:59Z" level=info msg="Owncast v0.1.1-linux-arm64 (103d1684ca329cbffdaa66bc5a17b064a20c5942)"
owncast-njionlive  | time="2023-09-12T11:21:59Z" level=info msg="Web server is listening on port 8080."
owncast-njionlive  | time="2023-09-12T11:21:59Z" level=info msg="Configure this server by visiting /admin."
owncast-njionlive  | time="2023-09-12T13:02:27Z" level=info msg="Owncast v0.1.1-linux-arm64 (103d1684ca329cbffdaa66bc5a17b064a20c5942)"
owncast-njionlive  | time="2023-09-12T13:02:27Z" level=info msg="RTMP is accepting inbound streams on port 1950."
owncast-njionlive  | time="2023-09-12T13:02:27Z" level=info msg="Web server is listening on port 8080."
owncast-njionlive  | time="2023-09-12T13:02:27Z" level=info msg="Configure this server by visiting /admin."
owncast-njionlive  | panic: runtime error: invalid memory address or nil pointer dereference
owncast-njionlive  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x578b78]
owncast-njionlive  |
owncast-njionlive  |
owncast-njionlive  | goroutine 105 [running]:
owncast-njionlive  | net/url.(*URL).String(0x0)
owncast-njionlive  | 	/usr/local/go/src/net/url/url.go:800 +0x28
owncast-njionlive  | github.com/owncast/owncast/activitypub/inbox.handleLikeRequest({0x1948700?, 0x0?}, {0x4d37368, 0x4000898840})
owncast-njionlive  | 	/build/activitypub/inbox/like.go:16 +0x74
owncast-njionlive  | github.com/go-fed/activity/streams.JSONResolver.Resolve.func1({0x40000ef38c, 0x4})
owncast-njionlive  | 	/go/pkg/mod/github.com/owncast/activity@v1.0.1-0.20211229051252-7821289d4026/streams/gen_json_resolver.go:559 +0x33c0
owncast-njionlive  | github.com/go-fed/activity/streams.JSONResolver.Resolve({{0x400074fce0?, 0x1b1?, 0x4000acbde8?}}, {0x4d18bd8, 0x400003c078}, 0x4000cef4d0)
owncast-njionlive  | 	/go/pkg/mod/github.com/owncast/activity@v1.0.1-0.20211229051252-7821289d4026/streams/gen_json_resolver.go:888 +0x118
owncast-njionlive  | github.com/owncast/owncast/activitypub/resolvers.Resolve({0x4d18bd8, 0x400003c078}, {0x4000928400, 0x1b1, 0x200}, {0x400074fce0?, 0x0?, 0xeb?})
owncast-njionlive  | 	/build/activitypub/resolvers/resolve.go:35 +0x104
owncast-njionlive  | github.com/owncast/owncast/activitypub/inbox.handle({0x4000968000, {0x40009dc076, 0x9}, {0x4000928400, 0x1b1, 0x200}})
owncast-njionlive  | 	/build/activitypub/inbox/worker.go:32 +0x1d0
owncast-njionlive  | github.com/owncast/owncast/activitypub/inbox.worker(0x1?, 0x2?)
owncast-njionlive  | 	/build/activitypub/inbox/workerpool.go:40 +0xbc
owncast-njionlive  | created by github.com/owncast/owncast/activitypub/inbox.InitInboxWorkerPool
owncast-njionlive  | 	/build/activitypub/inbox/workerpool.go:26 +0x68
owncast-njionlive  | time="2023-09-13T17:36:02Z" level=info msg="Owncast v0.1.1-linux-arm64 (103d1684ca329cbffdaa66bc5a17b064a20c5942)"
owncast-njionlive  | time="2023-09-13T17:36:02Z" level=info msg="RTMP is accepting inbound streams on port 1950."
owncast-njionlive  | time="2023-09-13T17:36:02Z" level=info msg="Web server is listening on port 8080."
owncast-njionlive  | time="2023-09-13T17:36:02Z" level=info msg="Configure this server by visiting /admin."
owncast-njionlive  | panic: runtime error: invalid memory address or nil pointer dereference
owncast-njionlive  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x578b78]
owncast-njionlive  |
owncast-njionlive  |
owncast-njionlive  | goroutine 142 [running]:
owncast-njionlive  | net/url.(*URL).String(0x0)
owncast-njionlive  | 	/usr/local/go/src/net/url/url.go:800 +0x28
owncast-njionlive  | github.com/owncast/owncast/activitypub/inbox.handleLikeRequest({0x1948700?, 0x0?}, {0x4d37368, 0x400054cb00})
owncast-njionlive  | 	/build/activitypub/inbox/like.go:16 +0x74
owncast-njionlive  | github.com/go-fed/activity/streams.JSONResolver.Resolve.func1({0x4007a34738, 0x4})
owncast-njionlive  | 	/go/pkg/mod/github.com/owncast/activity@v1.0.1-0.20211229051252-7821289d4026/streams/gen_json_resolver.go:559 +0x33c0
owncast-njionlive  | github.com/go-fed/activity/streams.JSONResolver.Resolve({{0x40004f6fc0?, 0x1b1?, 0x400048fde8?}}, {0x4d18bd8, 0x4000144038}, 0x4000541c20)
owncast-njionlive  | 	/go/pkg/mod/github.com/owncast/activity@v1.0.1-0.20211229051252-7821289d4026/streams/gen_json_resolver.go:888 +0x118
owncast-njionlive  | github.com/owncast/owncast/activitypub/resolvers.Resolve({0x4d18bd8, 0x4000144038}, {0x4000282000, 0x1b1, 0x200}, {0x40004f6fc0?, 0x0?, 0x0?})
owncast-njionlive  | 	/build/activitypub/resolvers/resolve.go:35 +0x104
owncast-njionlive  | github.com/owncast/owncast/activitypub/inbox.handle({0x4000746100, {0x400805a0d6, 0x9}, {0x4000282000, 0x1b1, 0x200}})
owncast-njionlive  | 	/build/activitypub/inbox/worker.go:32 +0x1d0
owncast-njionlive  | github.com/owncast/owncast/activitypub/inbox.worker(0x1?, 0xd?)
owncast-njionlive  | 	/build/activitypub/inbox/workerpool.go:40 +0xbc
owncast-njionlive  | created by github.com/owncast/owncast/activitypub/inbox.InitInboxWorkerPool
owncast-njionlive  | 	/build/activitypub/inbox/workerpool.go:26 +0x68
owncast-njionlive  | time="2023-09-13T19:22:49Z" level=info msg="Owncast v0.1.1-linux-arm64 (103d1684ca329cbffdaa66bc5a17b064a20c5942)"
owncast-njionlive  | time="2023-09-13T19:22:49Z" level=info msg="RTMP is accepting inbound streams on port 1950."
owncast-njionlive  | time="2023-09-13T19:22:49Z" level=info msg="Web server is listening on port 8080."
owncast-njionlive  | time="2023-09-13T19:22:49Z" level=info msg="Configure this server by visiting /admin."
owncast-njionlive  | panic: runtime error: invalid memory address or nil pointer dereference
owncast-njionlive  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x578b78]
owncast-njionlive  |
owncast-njionlive  |
owncast-njionlive  | goroutine 128 [running]:
owncast-njionlive  | net/url.(*URL).String(0x0)
owncast-njionlive  | 	/usr/local/go/src/net/url/url.go:800 +0x28
owncast-njionlive  | github.com/owncast/owncast/activitypub/inbox.handleLikeRequest({0x1948700?, 0x0?}, {0x4d37368, 0x4000145080})
owncast-njionlive  | 	/build/activitypub/inbox/like.go:16 +0x74
owncast-njionlive  | github.com/go-fed/activity/streams.JSONResolver.Resolve.func1({0x400242e648, 0x4})
owncast-njionlive  | 	/go/pkg/mod/github.com/owncast/activity@v1.0.1-0.20211229051252-7821289d4026/streams/gen_json_resolver.go:559 +0x33c0
owncast-njionlive  | github.com/go-fed/activity/streams.JSONResolver.Resolve({{0x40003bf9e0?, 0x1b1?, 0x4000025de8?}}, {0x4d18bd8, 0x400003c078}, 0x40002cf560)
owncast-njionlive  | 	/go/pkg/mod/github.com/owncast/activity@v1.0.1-0.20211229051252-7821289d4026/streams/gen_json_resolver.go:888 +0x118
owncast-njionlive  | github.com/owncast/owncast/activitypub/resolvers.Resolve({0x4d18bd8, 0x400003c078}, {0x4000698000, 0x1b1, 0x200}, {0x40003bf9e0?, 0x0?, 0x40003eb498?})
owncast-njionlive  | 	/build/activitypub/resolvers/resolve.go:35 +0x104
owncast-njionlive  | github.com/owncast/owncast/activitypub/inbox.handle({0x4000490000, {0x4000718076, 0x9}, {0x4000698000, 0x1b1, 0x200}})
owncast-njionlive  | 	/build/activitypub/inbox/worker.go:32 +0x1d0
owncast-njionlive  | github.com/owncast/owncast/activitypub/inbox.worker(0x40003eb4d4?, 0x1?)
owncast-njionlive  | 	/build/activitypub/inbox/workerpool.go:40 +0xbc
owncast-njionlive  | created by github.com/owncast/owncast/activitypub/inbox.InitInboxWorkerPool
owncast-njionlive  | 	/build/activitypub/inbox/workerpool.go:26 +0x68
owncast-njionlive  | time="2023-09-14T03:07:52Z" level=info msg="Owncast v0.1.1-linux-arm64 (103d1684ca329cbffdaa66bc5a17b064a20c5942)"
owncast-njionlive  | time="2023-09-14T03:07:52Z" level=info msg="RTMP is accepting inbound streams on port 1950."
owncast-njionlive  | time="2023-09-14T03:07:52Z" level=info msg="Web server is listening on port 8080."
owncast-njionlive  | time="2023-09-14T03:07:52Z" level=info msg="Configure this server by visiting /admin."
owncast-njionlive  | panic: runtime error: invalid memory address or nil pointer dereference
owncast-njionlive  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x578b78]
owncast-njionlive  |
owncast-njionlive  |
owncast-njionlive  | goroutine 130 [running]:
owncast-njionlive  | net/url.(*URL).String(0x0)
owncast-njionlive  | 	/usr/local/go/src/net/url/url.go:800 +0x28
owncast-njionlive  | github.com/owncast/owncast/activitypub/inbox.handleLikeRequest({0x1948700?, 0x0?}, {0x4d37368, 0x40000f7600})
owncast-njionlive  | 	/build/activitypub/inbox/like.go:16 +0x74
owncast-njionlive  | github.com/go-fed/activity/streams.JSONResolver.Resolve.func1({0x400064c54c, 0x4})
owncast-njionlive  | 	/go/pkg/mod/github.com/owncast/activity@v1.0.1-0.20211229051252-7821289d4026/streams/gen_json_resolver.go:559 +0x33c0
owncast-njionlive  | github.com/go-fed/activity/streams.JSONResolver.Resolve({{0x40005d67e0?, 0x1b1?, 0x400043bde8?}}, {0x4d18bd8, 0x400003c078}, 0x40001fb1a0)
owncast-njionlive  | 	/go/pkg/mod/github.com/owncast/activity@v1.0.1-0.20211229051252-7821289d4026/streams/gen_json_resolver.go:888 +0x118
owncast-njionlive  | github.com/owncast/owncast/activitypub/resolvers.Resolve({0x4d18bd8, 0x400003c078}, {0x400026e000, 0x1b1, 0x200}, {0x40005d67e0?, 0x0?, 0x0?})
owncast-njionlive  | 	/build/activitypub/resolvers/resolve.go:35 +0x104
owncast-njionlive  | github.com/owncast/owncast/activitypub/inbox.handle({0x40009d6f00, {0x400001c5e6, 0x9}, {0x400026e000, 0x1b1, 0x200}})
owncast-njionlive  | 	/build/activitypub/inbox/worker.go:32 +0x1d0
owncast-njionlive  | github.com/owncast/owncast/activitypub/inbox.worker(0x0?, 0x0?)
owncast-njionlive  | 	/build/activitypub/inbox/workerpool.go:40 +0xbc
owncast-njionlive  | created by github.com/owncast/owncast/activitypub/inbox.InitInboxWorkerPool
owncast-njionlive  | 	/build/activitypub/inbox/workerpool.go:26 +0x68
owncast-njionlive  | time="2023-09-14T03:21:00Z" level=info msg="Owncast v0.1.1-linux-arm64 (103d1684ca329cbffdaa66bc5a17b064a20c5942)"
owncast-njionlive  | time="2023-09-14T03:21:00Z" level=info msg="RTMP is accepting inbound streams on port 1950."
owncast-njionlive  | time="2023-09-14T03:21:00Z" level=info msg="Web server is listening on port 8080."
owncast-njionlive  | time="2023-09-14T03:21:00Z" level=info msg="Configure this server by visiting /admin."
owncast-njionlive  | panic: runtime error: invalid memory address or nil pointer dereference
owncast-njionlive  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x578b78]
owncast-njionlive  |
owncast-njionlive  |
owncast-njionlive  | goroutine 129 [running]:
owncast-njionlive  | net/url.(*URL).String(0x0)
owncast-njionlive  | 	/usr/local/go/src/net/url/url.go:800 +0x28
owncast-njionlive  | github.com/owncast/owncast/activitypub/inbox.handleLikeRequest({0x1948700?, 0x0?}, {0x4d37368, 0x400066e000})
owncast-njionlive  | 	/build/activitypub/inbox/like.go:16 +0x74
owncast-njionlive  | github.com/go-fed/activity/streams.JSONResolver.Resolve.func1({0x400069113c, 0x4})
owncast-njionlive  | 	/go/pkg/mod/github.com/owncast/activity@v1.0.1-0.20211229051252-7821289d4026/streams/gen_json_resolver.go:559 +0x33c0
owncast-njionlive  | github.com/go-fed/activity/streams.JSONResolver.Resolve({{0x4002272c00?, 0x1b1?, 0x40005c9de8?}}, {0x4d18bd8, 0x400003c078}, 0x400038cd80)
owncast-njionlive  | 	/go/pkg/mod/github.com/owncast/activity@v1.0.1-0.20211229051252-7821289d4026/streams/gen_json_resolver.go:888 +0x118
owncast-njionlive  | github.com/owncast/owncast/activitypub/resolvers.Resolve({0x4d18bd8, 0x400003c078}, {0x400026aa00, 0x1b1, 0x200}, {0x4002272c00?, 0x0?, 0x0?})
owncast-njionlive  | 	/build/activitypub/resolvers/resolve.go:35 +0x104
owncast-njionlive  | github.com/owncast/owncast/activitypub/inbox.handle({0x4000605000, {0x40000bd666, 0x9}, {0x400026aa00, 0x1b1, 0x200}})
owncast-njionlive  | 	/build/activitypub/inbox/worker.go:32 +0x1d0
owncast-njionlive  | github.com/owncast/owncast/activitypub/inbox.worker(0x0?, 0x0?)
owncast-njionlive  | 	/build/activitypub/inbox/workerpool.go:40 +0xbc
owncast-njionlive  | created by github.com/owncast/owncast/activitypub/inbox.InitInboxWorkerPool
owncast-njionlive  | 	/build/activitypub/inbox/workerpool.go:26 +0x68
owncast-njionlive  | time="2023-09-14T09:40:50Z" level=info msg="Owncast v0.1.1-linux-arm64 (103d1684ca329cbffdaa66bc5a17b064a20c5942)"
owncast-njionlive  | time="2023-09-14T09:40:50Z" level=info msg="RTMP is accepting inbound streams on port 1950."
owncast-njionlive  | time="2023-09-14T09:40:50Z" level=info msg="Web server is listening on port 8080."
owncast-njionlive  | time="2023-09-14T09:40:50Z" level=info msg="Configure this server by visiting /admin."
owncast-njionlive  | panic: runtime error: invalid memory address or nil pointer dereference
owncast-njionlive  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x578b78]
owncast-njionlive  |
owncast-njionlive  |
owncast-njionlive  | goroutine 159 [running]:
owncast-njionlive  | net/url.(*URL).String(0x0)
owncast-njionlive  | 	/usr/local/go/src/net/url/url.go:800 +0x28
owncast-njionlive  | github.com/owncast/owncast/activitypub/inbox.handleLikeRequest({0x1948700?, 0x0?}, {0x4d37368, 0x4000fd6580})
owncast-njionlive  | 	/build/activitypub/inbox/like.go:16 +0x74
owncast-njionlive  | github.com/go-fed/activity/streams.JSONResolver.Resolve.func1({0x400235f8dc, 0x4})
owncast-njionlive  | 	/go/pkg/mod/github.com/owncast/activity@v1.0.1-0.20211229051252-7821289d4026/streams/gen_json_resolver.go:559 +0x33c0
owncast-njionlive  | github.com/go-fed/activity/streams.JSONResolver.Resolve({{0x4000ce16e0?, 0x1b1?, 0x4000661de8?}}, {0x4d18bd8, 0x400003c078}, 0x4001f85920)
owncast-njionlive  | 	/go/pkg/mod/github.com/owncast/activity@v1.0.1-0.20211229051252-7821289d4026/streams/gen_json_resolver.go:888 +0x118
owncast-njionlive  | github.com/owncast/owncast/activitypub/resolvers.Resolve({0x4d18bd8, 0x400003c078}, {0x400079e200, 0x1b1, 0x200}, {0x4000ce16e0?, 0x0?, 0x0?})
owncast-njionlive  | 	/build/activitypub/resolvers/resolve.go:35 +0x104
owncast-njionlive  | github.com/owncast/owncast/activitypub/inbox.handle({0x4001c10e00, {0x4002296976, 0x9}, {0x400079e200, 0x1b1, 0x200}})
owncast-njionlive  | 	/build/activitypub/inbox/worker.go:32 +0x1d0
owncast-njionlive  | github.com/owncast/owncast/activitypub/inbox.worker(0x0?, 0x1b3a11e?)
owncast-njionlive  | 	/build/activitypub/inbox/workerpool.go:40 +0xbc
owncast-njionlive  | created by github.com/owncast/owncast/activitypub/inbox.InitInboxWorkerPool
owncast-njionlive  | 	/build/activitypub/inbox/workerpool.go:26 +0x68
owncast-njionlive  | time="2023-09-14T13:48:12Z" level=info msg="Owncast v0.1.1-linux-arm64 (103d1684ca329cbffdaa66bc5a17b064a20c5942)"
owncast-njionlive  | time="2023-09-14T13:48:12Z" level=info msg="RTMP is accepting inbound streams on port 1950."
owncast-njionlive  | time="2023-09-14T13:48:12Z" level=info msg="Web server is listening on port 8080."
owncast-njionlive  | time="2023-09-14T13:48:12Z" level=info msg="Configure this server by visiting /admin."
owncast-njionlive  | time="2023-09-14T17:42:20Z" level=info msg="Inbound stream connected."
owncast-njionlive  | time="2023-09-14T17:42:20Z" level=info msg="Processing video using codec x264 with 2 output qualities configured."
owncast-njionlive  | time="2023-09-14T17:51:02Z" level=info msg="Inbound stream disconnected."
owncast-njionlive  | time="2023-09-14T17:52:00Z" level=info msg="Inbound stream connected."
owncast-njionlive  | time="2023-09-14T17:52:00Z" level=info msg="Processing video using codec x264 with 2 output qualities configured."
owncast-njionlive  | panic: runtime error: invalid memory address or nil pointer dereference
owncast-njionlive  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x578b78]
owncast-njionlive  |
owncast-njionlive  |
owncast-njionlive  | goroutine 153 [running]:
owncast-njionlive  | net/url.(*URL).String(0x0)
owncast-njionlive  | 	/usr/local/go/src/net/url/url.go:800 +0x28
owncast-njionlive  | github.com/owncast/owncast/activitypub/inbox.handleLikeRequest({0x1948700?, 0x0?}, {0x4d37368, 0x4000803340})
owncast-njionlive  | 	/build/activitypub/inbox/like.go:16 +0x74
owncast-njionlive  | github.com/go-fed/activity/streams.JSONResolver.Resolve.func1({0x400b7e453c, 0x4})
owncast-njionlive  | 	/go/pkg/mod/github.com/owncast/activity@v1.0.1-0.20211229051252-7821289d4026/streams/gen_json_resolver.go:559 +0x33c0
owncast-njionlive  | github.com/go-fed/activity/streams.JSONResolver.Resolve({{0x401d1d5260?, 0x1b1?, 0x4000dadde8?}}, {0x4d18bd8, 0x4000144038}, 0x4005f50e40)
owncast-njionlive  | 	/go/pkg/mod/github.com/owncast/activity@v1.0.1-0.20211229051252-7821289d4026/streams/gen_json_resolver.go:888 +0x118
owncast-njionlive  | github.com/owncast/owncast/activitypub/resolvers.Resolve({0x4d18bd8, 0x4000144038}, {0x4000e76000, 0x1b1, 0x200}, {0x401d1d5260?, 0x0?, 0x0?})
owncast-njionlive  | 	/build/activitypub/resolvers/resolve.go:35 +0x104
owncast-njionlive  | github.com/owncast/owncast/activitypub/inbox.handle({0x400f6c4d00, {0x400c9cc7f6, 0x9}, {0x4000e76000, 0x1b1, 0x200}})
owncast-njionlive  | 	/build/activitypub/inbox/worker.go:32 +0x1d0
owncast-njionlive  | github.com/owncast/owncast/activitypub/inbox.worker(0x0?, 0x0?)
owncast-njionlive  | 	/build/activitypub/inbox/workerpool.go:40 +0xbc
owncast-njionlive  | created by github.com/owncast/owncast/activitypub/inbox.InitInboxWorkerPool
owncast-njionlive  | 	/build/activitypub/inbox/workerpool.go:26 +0x68
owncast-njionlive  | time="2023-09-14T19:21:15Z" level=info msg="Owncast v0.1.1-linux-arm64 (103d1684ca329cbffdaa66bc5a17b064a20c5942)"
owncast-njionlive  | time="2023-09-14T19:21:15Z" level=info msg="RTMP is accepting inbound streams on port 1950."
owncast-njionlive  | time="2023-09-14T19:21:15Z" level=info msg="Web server is listening on port 8080."
owncast-njionlive  | time="2023-09-14T19:21:15Z" level=info msg="Configure this server by visiting /admin."
owncast-njionlive  | time="2023-09-14T19:21:18Z" level=info msg="Inbound stream connected."
owncast-njionlive  | time="2023-09-14T19:21:18Z" level=info msg="Processing video using codec x264 with 2 output qualities configured."
```

**Comment by alyx161** [comment]
I just found #3223 and that it is already fixed by #3232 

Sorry for the spam 😅
