### ISSUE TITLE
invalid memory address error

### ISSUE THREAD

**Issue by darkdecoy** [owncast/owncast#3331]
### Share your bug report, feature request, or comment.

When trying to owncast v0.1.1 in docker container the container crashes as soon as a stream is sent to the owncast server with the following error...

```
Sep 26 22:04:14 parachutelive.tv systemd[1]: Started owncast-server.
Sep 26 22:04:18 parachutelive.tv owncast-server[2748]: time="2023-09-26T22:04:18Z" level=info msg="Moving custom emoji directory from webroot/img/emoji to data/emoji"
Sep 26 22:04:18 parachutelive.tv owncast-server[2748]: time="2023-09-26T22:04:18Z" level=warning msg="Moving with os.Rename failed, falling back to copy and delete! rename webroot/img/emoji data/emoji: invalid cross-device link"
Sep 26 22:04:18 parachutelive.tv owncast-server[2748]: time="2023-09-26T22:04:18Z" level=error msg="error moving custom emoji directory Writing to output file failed: write data/emoji: copy_file_range: is a directory"
Sep 26 22:04:18 parachutelive.tv owncast-server[2748]: time="2023-09-26T22:04:18Z" level=info msg="Owncast v0.1.1-linux-64bit (103d1684ca329cbffdaa66bc5a17b064a20c5942)"
Sep 26 22:04:18 parachutelive.tv owncast-server[2748]: time="2023-09-26T22:04:18Z" level=info msg="Web server is listening on port 8080."
Sep 26 22:04:18 parachutelive.tv owncast-server[2748]: time="2023-09-26T22:04:18Z" level=info msg="Configure this server by visiting /admin."
Sep 26 22:04:23 parachutelive.tv owncast-server[2748]: time="2023-09-26T22:04:23Z" level=info msg="Inbound stream connected."
Sep 26 22:04:23 parachutelive.tv owncast-server[2748]: panic: runtime error: invalid memory address or nil pointer dereference
Sep 26 22:04:23 parachutelive.tv owncast-server[2748]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x90f446]
Sep 26 22:04:23 parachutelive.tv owncast-server[2748]: goroutine 11 [running]:
Sep 26 22:04:23 parachutelive.tv owncast-server[2748]: github.com/owncast/owncast/core/data.UpdateEmojiList.func1({0x1cbd69f, 0x1}, {0x0, 0x0}, {0x0?, 0x0?})
Sep 26 22:04:23 parachutelive.tv owncast-server[2748]:         /build/core/data/emoji.go:51 +0x46
Sep 26 22:04:23 parachutelive.tv owncast-server[2748]: io/fs.WalkDir({0x4ea9760, 0xc0003d9840}, {0x1cbd69f, 0x1}, 0x3c2de50)
Sep 26 22:04:23 parachutelive.tv owncast-server[2748]:         /usr/local/go/src/io/fs/walk.go:110 +0x6a
Sep 26 22:04:23 parachutelive.tv owncast-server[2748]: github.com/owncast/owncast/core/data.UpdateEmojiList(0x0)
Sep 26 22:04:23 parachutelive.tv owncast-server[2748]:         /build/core/data/emoji.go:63 +0x25d
Sep 26 22:04:23 parachutelive.tv owncast-server[2748]: github.com/owncast/owncast/core/chat/events.loadEmoji()
Sep 26 22:04:23 parachutelive.tv owncast-server[2748]:         /build/core/chat/events/events.go:145 +0x45
Sep 26 22:04:23 parachutelive.tv owncast-server[2748]: github.com/owncast/owncast/core/chat/events.RenderMarkdown({0x1cff95d, 0x27})
Sep 26 22:04:23 parachutelive.tv owncast-server[2748]:         /build/core/chat/events/events.go:207 +0x5b
Sep 26 22:04:23 parachutelive.tv owncast-server[2748]: github.com/owncast/owncast/core/chat/events.(*MessageEvent).RenderBody(...)
Sep 26 22:04:23 parachutelive.tv owncast-server[2748]:         /build/core/chat/events/events.go:192
Sep 26 22:04:23 parachutelive.tv owncast-server[2748]: github.com/owncast/owncast/core/chat.SendSystemAction({0x1cff95d, 0x27}, 0x1)
Sep 26 22:04:23 parachutelive.tv owncast-server[2748]:         /build/core/chat/chat.go:146 +0x110
Sep 26 22:04:23 parachutelive.tv owncast-server[2748]: github.com/owncast/owncast/core.setStreamAsConnected(0xc000010bc0)
Sep 26 22:04:23 parachutelive.tv owncast-server[2748]:         /build/core/streamState.go:74 +0x2e5
Sep 26 22:04:23 parachutelive.tv owncast-server[2748]: github.com/owncast/owncast/core/rtmp.HandleConn(0xc000170f00, {0x4eb3618?, 0xc000262588})
Sep 26 22:04:23 parachutelive.tv owncast-server[2748]:         /build/core/rtmp/rtmp.go:105 +0x343
Sep 26 22:04:23 parachutelive.tv owncast-server[2748]: github.com/nareix/joy5/format/rtmp.(*Server).HandleNetConn(0xc0000aea80, {0x4eb3618?, 0xc000262588?})
Sep 26 22:04:23 parachutelive.tv owncast-server[2748]:         /go/pkg/mod/github.com/nareix/joy5@v0.0.0-20210317075623-2c912ca30590/format/rtmp/server.go:75 +0x3fc
Sep 26 22:04:23 parachutelive.tv owncast-server[2748]: created by github.com/owncast/owncast/core/rtmp.Start
Sep 26 22:04:23 parachutelive.tv owncast-server[2748]:         /build/core/rtmp/rtmp.go:62 +0x2d5
Sep 26 22:04:24 parachutelive.tv systemd[1]: owncast-server.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Sep 26 22:04:24 parachutelive.tv systemd[1]: owncast-server.service: Failed with result 'exit-code'.
```

When I revert back to version 0.1.0 then everthing works fine.

**Comment by gabek** [comment]
Looks like from the crash log there's an issue handling the custom emoji directory on disk. The "invalid cross device link" is often seen if you're using Docker and actions are trying to be done cross-volume in your container. You might want to look at your volumes configuration and see if this is the case.

**Comment by imorrish** [comment]
I had the same issue running in an LXC on Proxmox. /data/emoji was a file, not a folder. I just did the following in the data directory
rm emoji
mkdir emoji

**Comment by gabek** [comment]
Even though it's a filesystem related issue, we should handle this exception better, instead of crashing.
