### ISSUE TITLE
Panic on RTMP connection when codec is resolved to nil (Mevo camera)

### ISSUE THREAD

**Issue by mattdsteele** [owncast/owncast#340]
I don't have a ton of information yet, but wanted to start the conversation. I've been playing with a [Mevo Start camera](https://mevo.com/pages/mevo-camera) - it's pretty neat so far, and supports generic RTMP connections.

When I try to connect to my Owncast instance, it crashes the server. Running with `--enableVerboseLogging --enableDebugFeatures` shows a few interesting bits:

`panic: interface conversion: interface {} is nil, not string`

Full logs:

```
INFO[2020-11-12T04:18:13Z]/root/owncast/core/rtmp/rtmp.go:90 github.com/owncast/owncast/core/rtmp.HandleConn() Incoming RTMP connected.                     
TRAC[2020-11-12T04:18:13Z]/root/owncast/yp/yp.go:81 github.com/owncast/owncast/yp.(*YP).ping() Pinging YP as:  Matt Steele                  
WARN[2020-11-12T04:18:14Z]/root/owncast/yp/yp.go:112 github.com/owncast/owncast/yp.(*YP).ping() YP Ping error returned from service: there was an error registering this instance email gabek@real-ity.com to have him look into it 
TRAC[2020-11-12T04:18:14Z]/root/owncast/core/ffmpeg/transcoder.go:82 github.com/owncast/owncast/core/ffmpeg.(*Transcoder).Start() Video transcoder started with 2 stream variants. 
INFO[2020-11-12T04:18:14Z]/root/owncast/core/ffmpeg/transcoder.go:85 github.com/owncast/owncast/core/ffmpeg.(*Transcoder).Start() /usr/bin/ffmpeg -hide_banner -loglevel warning -i  /tmp/streampipe.flv  -map v:0 -c:v:0 libx264 -b:v:0 4500k -maxrate:v:0 4770k -bufsize:v:0 5400k -g:v:0 119 -x264-params:v:0 "scenecut=0:open_gop=0:min-keyint=119:keyint=119" -map a:0 -c:a:0 copy -r 30 -preset veryfast -map v:0 -c:v:1 libx264 -b:v:1 800k -maxrate:v:1 848k -bufsize:v:1 960k -g:v:1 119 -x264-params:v:1 "scenecut=0:open_gop=0:min-keyint=119:keyint=119" -map a:0 -c:a:1 copy -r 30 -preset veryfast  -var_stream_map "v:0,a:0 v:1,a:1 " -f hls -hls_time 4 -hls_list_size 5 -hls_delete_threshold 10  -tune zerolatency -pix_fmt yuv420p -profile:v high -sc_threshold 0 -master_pl_name stream.m3u8 -strftime 1 -hls_segment_filename http://127.0.0.1:8081/%v/stream-PziiZRTMR%s.ts -max_muxing_queue_size 400 -method PUT -http_persistent 0 -fflags +genpts http://127.0.0.1:8081/%v/stream.m3u8 2> transcoder.log 
TRAC[2020-11-12T04:18:14Z]/root/owncast/core/rtmp/rtmp.go:71 github.com/owncast/owncast/core/rtmp.HandleConn.func1() [Type AMF0 Time 0 Len 543 Data ["@setDataFrame","onMetaData",{"author":"Mevo by Livestream","copyright":"Livestream Inc.","description":"","keywords":"","rating":"","title":"Custom RTMP","presetname":"Custom","creationdate":"Thu Nov 12 4:18:13 2020","videodevice":"","framerate":30,"width":640,"height":360,"videocodecid":"avc1","videodatarate":300,"avclevel":40,"avcprofile":77,"videokeyframe_frequency":2,"audiodevice":"Mevo","audiosamplerate":48000,"audiochannels":2,"audioinputvolume":100,"audiocodecid":"mp4a","audiodatarate":64}] Header ] 
TRAC[2020-11-12T04:18:14Z]/root/owncast/core/rtmp/rtmp.go:71 github.com/owncast/owncast/core/rtmp.HandleConn.func1() [Type AMF0 Time 0 Len 2059 Data ["@setJunkData","onJunkData",{"buffer":"ۍ\ufffdL\u001a\u0004\ufffdTi\ufffd\u0026\ufffd\ufffd=\ufffd\ufffd,\ufffd\u0014\ufffd\ufffd\ufffd\ufffd\u001eeq\ufffd2L\u003cx\ufffd\ufffd}ra\ufffd\u0006\ufffdh\u001d\ufffd\u0016\ufffd\ufffd7CA=\ufffd\ufffd\ufffd\ufffd\u000f)\ufffd\ufffdK\ufffd\ufffdp+\ufffd\ufffd\ufffd\ufffdf?\ufffd\ufffd\ufffd\ufffd.\ufffd\ufffd\ufffd\ufffdEW\u001e\n䜱d\ufffd\u000b.'[\ufffdR(\ufffd\\td\u001b\ufffdf\ufffdq\ufffd\ufffdp\u0003H+G\ufffdHσd\u0001f\ufffd\u000b\u0013\ufffd\ufffd/\u001f\ufffd-\ufffd\u0011\u0015'vE\u0017\ufffd\ufffd\ufffd\u000b\ufffd\ufffd\ufffd\u0007x\ufffd\t[ \ufffd\u0002\ufffd\ufffdύ\ufffdm\u0018Z\ufffd\u0016jz\u003c_?S\ufffd\ufffd\ufffdq\ufffd\tB\ufffd\u0001aU[\ufffdBܨ\ufffd\ufffd5n\ufffd\ufffd\ufffd~\ufffd\ufffdw\ufffd\u000f\ufffd\ufffdv\ufffdG\ufffd\\O(\ufffd\ufffd\u0008\ufffd*\ufffd\ufffd\ufffd/\ufffd\ufffd\ufffdF.3C\ufffd\ufffd\ufffd*po\u0019\ufffd\ufffd\ufffdL^\ufffd\ufffd\ufffd{\ufffd\u0002$\u0001\ufffd\ufffd0?W\ufffd\ufffd\u001c\ufffd\ufffd\ufffdL\u003e\ufffd\ufffd-\ufffd\u000e\ufffd\tk\ufffdf\u0017\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd,\\yj2\ufffd\u0014\ufffd\ufffdo\ufffd\ufffd\ufffdC\ufffd\ufffdH\u0014k\ufffd~ǵ\ufffd\ufffd \ufffdߌZ)\ufffd5!\"橴\ufffd\ufffd\ufffd^\ufffd\ufffd \t\ufffdg\ufffd\ufffd7\ufffd\ufffdl.n\ufffd\ufffd\ufffd\u0017\ufffdt\ufffd`\ufffdoF\ufffd#x\ufffdEխ\u0014t5\ufffd\ufffd\ufffdˑj\ufffd\ufffd\u0017\ufffd\ufffdi\ufffd\u001e\ufffdN\ufffdtaZ\ufffd\u001e\ufffd\ufffdIA\ufffduT\ufffd\ufffd\ufffdU\ufffd\ufffde\ufffdz\ufffdx\ufffd\ufffdac\u0006\ufffd1\ufffdh\ufffdʡ\ufffd\ufffdRv\u0008W\ufffd\ufffd\ufffd\u0014\ufffd%\r\ufffd\nn\ufffdj\ufffdBRF$ֺT\ufffd\"\ufffd\u0012B\u0013ד\t^\ufffd\ufffd\ufffd:\ufffd\ufffdޑ_\ufffd~\u0018Qd\ufffd\")\ufffd\ufffd\ufffdP?\ufffd\ufffdP\ufffdƦ\ufffdN\u0005BA\ufffd{E\ufffdYV9\ufffd\ufffdP\u0010\ufffd\ufffd\ufffdߣ\ufffd\ufffdrfĥ\ufffd\ufffdk\ufffdb\ufffd\ufffd#y\u001a\ufffd\ufffd\ufffd\ufffd\u0013\ufffd\ufffdf|E\u001c#t\ufffdE\ufffd\u003c\ufffd\u0001\ufffd[5\tF\u0010\ufffd~m\u000cv\u0007\ufffd\ufffdz\u001fE\u0026S\ufffd\ufffd\u0017\ufffdD\ufffd@\ufffd\u0026\ufffd\ufffd\ufffdy\u0019\ufffd\u0002\ufffdi\ufffd\ufffdVvP\\\ufffd\ufffdռ\ufffdz\ufffd4ޯs\ufffdT\ufffd\ufffd\ufffdf\u003cTg\u0019\ufffd\ufffds\u0012FB\ufffd\ufffd\ufffdA\u001f\ufffd\ufffd\ufffdxV\ufffd,\ufffd\ufffd\ufffd\ufffd\ufffd\u000b\u003cMpw\ufffdV\u000f\ufffd\u0026\ufffdm\ufffdCY\ufffd\u0006\ufffdm\u000fԙ\u0006*j1\ufffdi\ufffdt\u003c\ufffd/\u0008\ufffd%\ufffd\ufffd4\ufffdB4\ufffd-v\ufffd{|a\ufffd\n5\ufffd\u000f\ufffdi@9ю-\ufffd\ufffd[\ufffd\ufffd\ufffd;\ufffd3=\u000c\ufffd,9\\\ufffd3Wә`\ufffd\ufffd\ufffde\u0001-\ufffdѺJܠ\ufffdpͣ+\ufffd\ufffd\ufffd#\ufffd\ufffdږ\ufffd\rlץK_=8D\ufffdea\r\ufffd\ufffd\ufffd?N؋q\ufffd\ufffdFhĀ\ufffd\ufffd\ufffd\ufffd\ufffd\u0001U\ufffdK\ufffd\ufffd\ufffdvFg\ufffdR\u0005\ufffd:\ufffdN\ufffdN\ufffd\u0013o\ufffd\ufffd3\ufffd\ufffdP\u0018qy\u0019\ufffdG\ufffd\ufffd\ufffden\ufffd\ufffdD\ufffdPD\ufffd\u0012\u00111\ufffd\ufffd\ufffdMмS\ufffdNk!\ufffd\u0003e\ufffd\ufffd\\\ufffd\ufffd\ufffdp\u0014\ufffdVc\ufffduu\ufffd\ufffdS.g\ufffd}$\ufffd\ufffdSl\ufffd\ufffd2\u003cW\u003e\ufffd\ufffd\u0019h\ufffd\t|\ufffd^^\ufffd\ufffdR7\ufffd\ufffdd\ufffd\ufffd`\u0001\ufffd0\ufffdMi\ufffd\ufffd\ufffd\ufffd\u003cD\ufffd\ufffd+\ufffd\ufffd\u0026͹\ufffd\ufffd\u000b\ufffdZ\u0002\ufffd=\ufffd=\ufffd^\ufffd\ufffd0j\ufffds\ufffd\ufffd\r#\u001c\ufffdvG\u001eQ\ufffd\ufffd\ufffdo\u000f\ufffd\ufffdh\u0015=\ufffdrzB\ufffd\u0018\ufffd~\u0001Bp\ufffd\u001b|\ufffd\ufffd\ufffd\ufffd{\ufffd\ufffdgZ\ufffdUhl\u0019O\ufffdV\ufffdqO\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd,M\u001c'\ufffd\ufffd\ufffdV\ufffdh\ufffd\ufffd\ufffd~\u0007\ufffdi\ufffd\ufffdisjYA\ufffd\ufffd\u0026_T\ufffd\ufffd\ufffd\ufffd\ufffd\u0026.M\u001f\ufffd\u0018\ufffd)I\ufffd\u0026Op\ufffdl\ufffd\ufffd_Pϟ\ufffdg\ufffdL\ufffdϬ\ufffd\ufffd\ufffd\ufffdT\ufffd~׋\ufffd\ufffdK\ufffd\ufffd:4\ufffd \ufffd\ufffdpy\ufffd\ufffd\ufffdΨ\u001b\ufffdTT\ufffd{\ufffd\u0017\ufffd0m\ufffd3\ufffdL~\u0010\ufffd\ufffdCy\ufffdl\ufffd\ufffd\ufffdn\ufffdE\ufffd\ufffd_؜2\ufffd\u0017\ufffd1\ufffd\ufffd\ufffd}ň\ufffd4\ufffdZ-\ufffd\ufffd\u0010\u0016+\ufffd7o\ufffd\u0001M\u0010\u001c\ufffd\ufffd3\ufffd\ufffd6\ufffdw\ufffd\ufffd~\ufffdz\ufffd.soZ\ufffd5\ufffdW\ufffd\ufffd\ufffdM\u001d\u000e\u0019,)\u0016U\ufffdu\ufffd\u0011h\ufffd\ufffd \ufffd\u003c\u00197i\u000c\ufffdBMY*\ufffd7\ufffd\ufffd\u0003*\ufffd\u001b\ufffd毨A$VQ\u000b\ufffd\ufffd\ufffd\u001b\ufffdBQ\ufffdMuv\u0019\ufffd \u003c\ufffd\ufffd\ufffd\ufffdW*\u001f\ufffd\u0011\ufffdSQp(!\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u000c\ufffd\ufffd\ufffd+\ufffd\ufffdJ\u0005Ovq\ufffdL\ufffdq\ufffd*\ufffdI\ufffd-p\u001a\ufffd\ufffdLJKK.V\ufffd\ufffdU\ufffd'\ufffd\ufffd\ufffdn\ufffd\u001b\ufffd3\ufffd1)^\ufffd\ufffdX\ufffd\ufffd\ufffd@p\u003c\ufffd\ufffd\ufffd7\ufffd\u0005\ufffde\ufffd\ufffd\ufffd\u001ed\ufffd\u0005\ufffd2\ufffd3c_\ufffd\ufffdOg\ufffd\ufffdX)\u001f\ufffd1Y\ufffd\ufffdh\ufffdzLȳ\ufffde\u0018B\ufffd\ufffds\ufffd\ufffdU\ufffd\ufffd%\ufffd\u003e\rz\u0015\ufffd\u0018'e\ufffd\ufffdKW\ufffdE\ufffd$\ufffds\ufffd\ufffd4q\ufffd\ufffd\ufffdi\ufffd\ufffd\ufffd \ufffd\ufffd\ufffdP\ufffd\ufffd\ufffd\ufffdD\ufffdv\u000e-\ufffd\ufffdO\ufffd\ufffdA\ufffd\ufffdtly\u001a\ufffda\ufffd\u0006 \ufffdۛޫ+\ufffd\ufffda\ufffdgV\r\u0013\u0026\ufffd\ufffd\ufffd'!\ufffd|\ufffdt-\ufffd\ufffd\ufffd}t\ufffdX\ufffdQ\ufffd9\ufffd\u0014\ufffd\r\ufffdn\ufffd\ufffd\ufffd\ufffdk\ufffd\ufffd\ufffd@\u0018\ufffd\u003e\u000c\ufffd6\ufffd\u000b\ufffd\ufffd~\ufffd\ufffd\ufffd\u000c\u001b\\\u001f3痡\ufffd\"\ufffd\ufffd\ufffd`\ufffd\ufffd\u001f)4\\4}\ufffd\ufffd\ufffdC\ufffd\u0006K\ufffdSVa\ufffd\ufffd\ufffd\u0016\ufffd\ufffd\u0015\ufffd\ufffd\u000b\ufffdF\ufffdL\ufffdC?v|O\t\u0004\u0011\ufffd\ufffd\\5Z\ufffd\ufffd\t\ufffd\ufffd\ufffd\ufffdڱ\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd[i\u0019Y(\ufffd\ufffdv\u0017W\ufffd\ufffd\ufffd\ufffd\ufffd9\ufffdM\ufffd\ufffd\ufffd]\ufffd\ufffd\u000e\ufffd\u000eI̓\u001f'|\ufffd\ufffd\ufffdET\u0019۫\ufffd_\t\ufffd\u0018\ufffd\ufffd\ufffd\ufffd\ufffdWۯ\ufffdi첱\ufffd\ufffdO_@\u0005\ufffd\ufffdJ\ufffd\ufffd\ufffd\ufffd\u001a\u0003\ufffd\u001b\ufffd%.}$\ufffd\ufffd\ufffd'xh\ufffd*\ufffdK\ufffd\ufffd*\ufffd\ufffd\u0008\ufffd\ufffd9\nW\u0015\ufffdZy\ufffd\ufffd\ufffd\ufffd\ufffd\ufffda\ufffd?\u0007:\u0026\ufffd\ufffd\ufffdcO\ufffd\ufffd{\u000e\u0014\u000b\ufffdL\ufffd\ufffd\ufffd6pY\ufffd\ufffd\ufffd\\\ufffd5=\ufffd\ufffdCK\u0019[\ufffdV\ufffdzx\ufffd\ufffd\ufffd\\Ũ\u0012\\\u0008\ufffd\ufffd`9\ufffd\ufffd\u0015\ufffd\ufffdQ\r{\u0013֔n\ufffdi\ufffd|\ufffd\ufffdqfP\ufffd\ufffdw\ufffd\u0006~\ufffdP]\ufffd{1\u0014w\ufffdン\ufffdZ\ufffdc[/\ufffd\ufffd\u000f\ufffd\ufffd\ufffd\ufffd5\ufffdG\ufffd\ufffd\ufffd\ufffdq\ufffdy\ufffd\ufffd\u000c\ufffd\u0008\ufffde\ufffd\ufffd\u003e\ufffd\ufffd\u0019.\ufffd\ufffd=T5\ufffd$iM\ufffd\ufffdn-\ufffd\ufffd\ufffd\u0011K\u001c\u001d-#\ufffd\u0011]\ufffdO\\4g\ufffd\u0007\ufffdFZ\t\ufffd\ufffd\ufffdAe\ufffd/\u0011\u0026\ufffdܶ\ufffdwR\u0004\ufffdۓuI\ufffd\ufffd|\ufffdڂ\u001c [\ufffd\u0014֔\ufffd;\ufffd\u0003K\ufffd\u000f\ufffd\ufffd\ufffd\u001d\ufffdh5\ufffd\ufffd\ufffd\ufffd\\\ufffdm\ufffd\ufffdn=\ufffd\ufffd\ufffd\u0007\u001e\ufffdZX\ufffd\ufffd\"\ufffd\ufffd\ufffd\ufffdNc\ufffd\ufffd\ufffd\ufffd0A?\ufffd;+\ufffd\u000f\ufffd\ufffd\ufffd\ufffdI\u0008\ufffd\u003ca\ufffd\ufffd=t\ufffd\ufffd\ufffd\u0005\ufffd\u001d*(\ufffd\ufffdWt\ufffda.\ufffd\u000e\ufffd\ufffdv=U\ufffd\ufffd\ufffd\ufffd%#J\ufffd\ufffd\ufffd\ufffdP{\ufffdl\ufffd \ufffd\u001cv\ufffd\ufffdW\ufffd0d\ufffd\ufffdY\ufffd\ufffd\u0017zJ\ufffd\ufffdm\ufffd\ufffd\ufffdO\u0003\ufffd\ufffd\ufffd\ufffd\ufffd\u0019\ufffd\t\u000fmXe\ufffd\u0007H\ufffd\ufffd\ufffd]\u0026\ufffd\ufffdoE\ufffd["}] Header ] 
panic: interface conversion: interface {} is nil, not string

goroutine 56 [running]:
github.com/owncast/owncast/core/rtmp.getVideoCodec(...)
        /root/owncast/core/rtmp/utils.go:53
github.com/owncast/owncast/core/rtmp.setCurrentBroadcasterInfo(0x12, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0000a3200, 0x80b, 0x80b, 0xc000528820, ...)
        /root/owncast/core/rtmp/broadcaster.go:25 +0x425
github.com/owncast/owncast/core/rtmp.HandleConn.func1(0xc001244601, 0x12, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0000a3200, 0x80b, 0x80b)
        /root/owncast/core/rtmp/rtmp.go:72 +0x1af
github.com/nareix/joy5/format/rtmp.(*Conn).ReadTag(0xc001244600, 0x12, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0000a3200, 0x80b, 0x80b, ...)
        /root/go/pkg/mod/github.com/nareix/joy5@v0.0.0-20200712071056-a55089207c88/format/rtmp/msg.go:558 +0x138
github.com/nareix/joy5/format/flv.ReadPacket(0xc00057fc60, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/go/pkg/mod/github.com/nareix/joy5@v0.0.0-20200712071056-a55089207c88/format/flv/flv.go:234 +0x8b
github.com/nareix/joy5/format/rtmp.(*Conn).ReadPacket(0xc001244600, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/go/pkg/mod/github.com/nareix/joy5@v0.0.0-20200712071056-a55089207c88/format/rtmp/cmd.go:498 +0xe5
github.com/owncast/owncast/core/rtmp.HandleConn(0xc001244600, 0x11ff880, 0xc000010568)
        /root/owncast/core/rtmp/rtmp.go:112 +0x3c5
github.com/nareix/joy5/format/rtmp.(*Server).HandleNetConn(0xc00085d5c0, 0x11ff880, 0xc000010568)
        /root/go/pkg/mod/github.com/nareix/joy5@v0.0.0-20200712071056-a55089207c88/format/rtmp/server.go:75 +0x313
created by github.com/owncast/owncast/core/rtmp.Start
        /root/owncast/core/rtmp/rtmp.go:64 +0x226
```

The error itself is weird. This invocation of `getVideoCodec` at https://github.com/owncast/owncast/blob/master/core/rtmp/broadcaster.go#L25 makes me think it should be using this metadata which I see earlier in the logs, and is definitely not nil: `"videocodecid":"avc1"`

Anything obvious I'm missing?

**Comment by gabek** [comment]
That looks super cool, thanks for trying it out!  I think you pretty much narrowed it down, it is not nil... the first time!  But a second `AMF0` "junk data" tag comes in immediately afterward, where it is nil.  I've never seen that before.  Junk indeed!  I'm curious what that's all about.

I'm guessing that first valid `AMF0` tag is working fine, but then we crash when trying to find data in "junk data" afterward.  I think we just need to make sure that `getInboundDetailsFromMetadata` is returning what we expect before trying to use it.

Let me know if you want to try fixing this, since you can test it.  Otherwise I'm sure I could patch it up and let you know.

**Comment by gabek** [comment]
Also, unrelated: I saw the error registering to the YP service.  I'm assuming it's due to a key mismatch, so I just wiped your record.  Hopefully that fixes itself now!

**Comment by mattdsteele** [comment]
I’ll try and fix, just wanted another set of eyes before I started debugging. Thanks!
