### ISSUE TITLE
Admin throwing fatal error

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#3775]
### Share your bug report, feature request, or comment.

When accessing the admin, it's now throwing a fatal error. It's not actually experiencing a connectivity error, but some other error looks to be bubbling up and the web app is interpreting it as a connectivity issue.

![image](https://github.com/owncast/owncast/assets/414923/f7970904-d76e-4604-b490-d56179eb79a2)

The only error (though it's technically only a warning) is the following `defaultProps` warning, and I'm not sure if it's connected.
```
 ✓ Compiled /admin in 9.2s (3659 modules)
Warning: TextFieldWithSubmit: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
    at TextFieldWithSubmit (webpack-internal:///./components/admin/TextFieldWithSubmit.tsx:30:32)
    at div
    at header
    at eval (webpack-internal:///./node_modules/antd/es/layout/layout.js:63:27)
    at eval (webpack-internal:///./node_modules/antd/es/layout/layout.js:47:72)
    at section
    at eval (webpack-internal:///./node_modules/antd/es/layout/layout.js:77:65)
    at eval (webpack-internal:///./node_modules/antd/es/layout/layout.js:47:72)
    at section
    at eval (webpack-internal:///./node_modules/antd/es/layout/layout.js:77:65)
    at eval (webpack-internal:///./node_modules/antd/es/layout/layout.js:47:72)
    at MainLayout (webpack-internal:///./components/admin/MainLayout.tsx:137:23)
    at AlertMessageProvider (webpack-internal:///./utils/alert-message-context.tsx:16:33)
    at ServerStatusProvider (webpack-internal:///./utils/server-status-context.tsx:125:33)
    at AdminLayout (webpack-internal:///./components/layouts/AdminLayout.tsx:14:24)
    at App (webpack-internal:///./pages/_app.tsx:30:16)
    at StyleRegistry (/home/gabek/src/owncast2/web/node_modules/styled-jsx/dist/index/index.js:449:36)
    at eU (/home/gabek/src/owncast2/web/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:8:20468)
    at eH (/home/gabek/src/owncast2/web/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:17:1765)
    at eJ (/home/gabek/src/owncast2/web/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:17:3068)
    at div
    at e9 (/home/gabek/src/owncast2/web/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:26:761)
```

**Comment by mahmed2000** [comment]
That modal with that message explicitly checks if the server status context has an error, and is of error type `OWNCAST_SERVICE_UNREACHABLE` (string, === match). That is only ever set if the repeating `/status` api calls result is an `instanceof Error`.

Nothing stands out that would cause that on the frontend. If you tested this locally, then I imagine this would be a backend issue instead. The logs say anything? Is this only on my bcrypt branch or does this happen generally on develop currently?

**Comment by gabek** [comment]
I didn't dig too deep into it, but I did also test on `develop` to see if it had anything to do with the hashed password branch, and I did experience it on develop as well. However, if I test on [`nightly`](https://nightly.owncast.tv) I'm not able to reproduce it, and that is updated with `develop` every night. There were no visible server-side issues, and there were no failed API calls in the browser when looking client side. I'm guessing it's something small, I'll track it down.

**Comment by gabek** [comment]
When switching browsers, I was no longer able to reproduce this, so it might be something cached in a single browser on my side.

**Comment by mahmed2000** [comment]
If you haven't wiped the cache yet, does the network log show the status api call as an error? Transferred in bytes or cached by the service worker?

**Comment by gabek** [comment]
Nope, there were no client-side errors in the browser. I saw nothing to explain it. The only thing wrong was the text field warning, and that wasn't within the browser.
