### ISSUE TITLE
Streaming issue introduced by #401

### ISSUE THREAD

**Issue by muesli** [owncast/owncast#419]
Just updated my instance to git master and I can't stream to it anymore:

```
time="2020-12-04T08:41:47Z" level=info msg="Incoming RTMP connected."
time="2020-12-04T08:41:47Z" level=error msg="Not a setDataFrame message"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0xbf25c1]

goroutine 55 [running]:
github.com/owncast/owncast/core.setStreamAsConnected.func1()
        /app/core/streamState.go:46 +0x41
created by github.com/owncast/owncast/core.setStreamAsConnected
        /app/core/streamState.go:44 +0x11a
```

**Comment by muesli** [comment]
Actually lookign at `streamState.go:46` this could also be related to #401. I should probably bisect this.

**Comment by muesli** [comment]
Ok, tracked it down: the problem starts occurring with #401.

**Comment by gabek** [comment]
What are you using to stream to it?  I haven't been able to reproduce it.

**Comment by muesli** [comment]
OBS, 1080p, 30fps, x264, 160kbit/s AAC.

**Comment by gabek** [comment]
I'm still not able to reproduce this using OBS and Master.  Could you provide the output from `--enableVerboseLogging` and streaming?

```
INFO[2020-12-04T23:01:06-08:00] Incoming RTMP connected.                     
TRAC[2020-12-04T23:01:06-08:00] [Type AMF0 Time 0 Len 411 Data ["@setDataFrame","onMetaData",{"duration":0,"fileSize":0,"width":1280,"height":720,"videocodecid":7,"videodatarate":4350,"framerate":60,"audiocodecid":10,"audiodatarate":160,"audiosamplerate":48000,"audiosamplesize":16,"audiochannels":2,"stereo":true,"2.1":false,"3.1":false,"4.0":false,"4.1":false,"5.1":false,"7.1":false,"encoder":"obs-output module (libobs version 26.0.2+dfsg1-1)"}] Header ] 
TRAC[2020-12-04T23:01:06-08:00] Video transcoder started with 2 stream variants. 
```

**Comment by gabek** [comment]
Looks like Prism's headers look different than other RTMP broadcasting clients.

Prism:
```
[Type AMF0 Time 0 Len 169 Data ["onMetaData",{"width":1920,"height":1080,"displayWidth":1920,"displayHeight":1080,"audiocodecid":10,"audiosamplerate":48000,"videocodecid":7}] Header ]
```
Others:
```
[Type AMF0 Time 0 Len 411 Data ["@setDataFrame","onMetaData",{"duration":0,"fileSize":0,"width":1280,"height":720,"videocodecid":7,"videodatarate":4350,"framerate":60,"audiocodecid":10,"audiodatarate":160,"audiosamplerate":48000,"audiosamplesize":16,"audiochannels":2,"stereo":true,"2.1":false,"3.1":false,"4.0":false,"4.1":false,"5.1":false,"7.1":false,"encoder":"obs-output module (libobs version 26.0.2+dfsg1-1)"}] Header ]
```

Now it makes more sense, and I can fix it up.
